make matplotlib optional
pysal/esda pull request #346
Opened 2024-08-02 21:32 UTC by james-willis

Right now matplotlib is an implicit dependency of the library. By moving the import statement inside the function that uses it, esda will no longer break consumers that dont take a dependency on matplotlib explicitly.

2024-08-02 21:58 UTC, knaaptime commented
good call

2024-08-03 00:41 UTC, gegen07 requested changes

2024-08-03 00:41 UTC, gegen07 commented on esda/moran.py
> +    from matplotlib import colors
Could you nest this LOC with try-except statement to assure that user has matplotlib installed in their environment, as done in [`topo`](https://github.com/pysal/esda/blob/a337fc42dbdb315181f6b93ee3935e76fb84aebe/esda/topo.py#L121)?

2024-08-05 23:19 UTC, jGaboardi commented
Let's also remove `matplotlib` from the [`312-min.yaml`](https://github.com/pysal/esda/blob/0388ad2d52e9d0f5e4bae7388f92c82238b14bbc/ci/312-min.yaml#L17) (minimal dependencies) CI environment.

2024-08-05 23:23 UTC, jGaboardi commented
And move `matplotlib ` from [`project.optional-dependencies.tests`](https://github.com/pysal/esda/blob/0388ad2d52e9d0f5e4bae7388f92c82238b14bbc/pyproject.toml#L56C6-L56C16) into [`project.optional-dependencies.plus`](https://github.com/pysal/esda/blob/0388ad2d52e9d0f5e4bae7388f92c82238b14bbc/pyproject.toml#L48)

2024-08-06 02:41 UTC, jGaboardi approved these changes

2024-08-06 03:21 UTC, merged

2024-08-06 06:27 UTC, martinfleis commented
@jGaboardi if you want to have an env without matplotlib in min, we'll need to change geopandas to geopandas-base. Otherwise geopandas will pull it no matter if it is listed in our yaml file.

2024-08-06 11:27 UTC, jGaboardi commented
> @jGaboardi if you want to have an env without matplotlib in min, we'll need to change geopandas to geopandas-base. Otherwise geopandas will pull it no matter if it is listed in our yaml file.

Good call.